import { User } from "./User";

export class Repository{

    constructor(
        public id: number,
        public node_id: number,
        public name: string,
        public full_name: string,
        public privated: boolean,
        public owner: Array<User>,
        public html_url: string,
        public description: string,
        public fork: boolean,
        public url: string,
        public forks_url: string,
        public keys_url: string,
        public collaborators_url: StringConstructor,
        public teams_url: string,
        public hooks_url: string,
        public issue_events_url: string,
        public events_url: string,
        public assignees_url: string,
        public branches_url: string,
        public tags_url: string,
        public blobs_url: string,
        public git_tags_url: string,
        public git_refs_url: string,
        public trees_url: string,
        public statuses_url: string,
        public languages_url: string,
        public stargazers_url: string,
        public contributors_url: string,
        public subscribers_url: string,
        public subscription_url: string,
        public commits_url: string,
        public git_commits_url: string,
        public comments_url: string,
        public issue_comment_url: string,
        public contents_url: string,
        public compare_url: string,
        public merges_url: string,
        public archive_url: string,
        public downloads_url: string,
        public issues_url: string,
        public pulls_url: string,
        public milestones_url: string,
        public notifications_url: string,
        public labels_url: string,
        public releases_url: string,
        public deployments_url: string
    ){}
}